### ISSUE TITLE
Build with Qt6

### ISSUE THREAD

**Issue by Harold2017** [czyt1988/QWT#1]
Hi, thanks for your great work for porting qwt from qmake to cmake.
But i wonder will it work well with Qt6 without changes in codes or maybe some module like `Core5Compat`?

**Comment by Harold2017** [comment]
Thanks for your reply.
My former concern is about the compatibility with Qt6. And i just want to confirm it before a manually full compilation. 
Yesterday i installed `qwt` with [`vcpkg` port](https://vcpkg.roundtrip.dev/ports/qwt) and found it works well with `Qt6.5`.
So there should be no compatibility problems.
Btw, `vcpkg` still used `qmake` for building `qwt`, and i will try your `cmake` version later.
Thanks.

**Comment by Harold2017** [comment]
solved and closed.

**Comment by czyt1988** [comment]
> solved and closed.

The latest version already supports qt5 and qt6
